on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

name: render-paper

jobs:
  render-paper:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 2
      - uses: r-lib/actions/setup-tinytex@v2
      - name: Render PDF
        run: |
          renv::load()
          rmarkdown::render("paper/paper.Rmd", output_dir = "paper")
        shell: Rscript {0}
      - name: Render PDF for submission
        run: |
          renv::load()
          rmarkdown::render(
            "paper/paper.Rmd", output_dir = "paper/submission",
            params = list(preprint = FALSE)
          )
        shell: Rscript {0}
      - name: Render HTML
        run: |
          renv::load()
          rmarkdown::render(
            "paper/paper.Rmd", output_dir = "paper",
            output_format = "bookdown::html_document2"
          )
        shell: Rscript {0}
      - name: Upload
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./paper

  # Deployment job
  publish-paper:
    if: github.event_name != 'pull_request'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: render-paper
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1