on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

name: render-paper

jobs:
  render-paper:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 2
      - uses: r-lib/actions/setup-tinytex@v2
      - name: Render
        run: |
          renv::load()
          rmarkdown::render("paper/paper.Rmd", output_dir = "rendered-paper")
        shell: Rscript {0}
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: paper
          retention-days: 5
          path: rendered-paper

  publish-paper:
    if: github.ref == 'refs/heads/main' && github.repository == 'epiforecasts/simplfied-forecaster-evaluation'
    needs: render-paper
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v2
    - name: Make a clean gh-pages branch
      run: |
        git checkout --orphan gh-pages
        git rm -rf .
    - uses: actions/download-artifact@v2
      with:
        name: rendered-paper
        path: .
    - name: Commit and push
      run: |
        git config user.email "action@github.com"
        git config user.name "GitHub Action - Published paper"
        git add --all
        git commit -m "Published paper"
        git push -f origin gh-pages:gh-pages
        echo "paper published to GitHub"
